# ------------------------------------------------------------------------------
# reasons you might want to use `environment.yaml` instead of `requirements.txt`:
# - pip installs packages in a loop, without ensuring dependencies across all packages
#   are fulfilled simultaneously, but conda achieves proper dependency control
# - conda installs precompiled binaries, avoiding system-level compiler issues
#
# Usage:
#   mamba env create -f environment.yml
#   conda activate myria3d
#   pip install torch_geometric pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv \
#       -f https://data.pyg.org/whl/torch-2.7.0+cu128.html
# ------------------------------------------------------------------------------

name: myria3d

channels:
  - conda-forge
  - nvidia

dependencies:
  - python=3.10
  - pip

  # --- Deep Learning ---
  # TO-DO
  
  # --- Data Formats ---
  - numpy
  - h5py
  - pandas

  # --- Geospatial ---
  - pdal=2.7.*       # 2.9.* is not yet in conda-forge
  - python-pdal
  - gdal
  - pyproj
  - laspy=2.6.*

  # --- Visualization ---
  - matplotlib
  - seaborn

  # --- Logging & Experiment Tracking ---
  - urllib3<2        # avoids compatibility issues
  - pre-commit
  - black
  - isort
  - flake8

  # --- Testing ---
  - pytest=8.4.*
  - pytest-cov=4.*
  - coverage=7.2.*

  # --- Developer Tools ---
  - python-dotenv
  - rich
  - pudb
  - twine

  # --- Documentation ---
  - sphinx=4.5.*
  - recommonmark=0.7.*
  - sphinx_rtd_theme=1.0.*
  - docutils=0.17
  - rstcheck=3.3.*

  - pip>=23
  - pip:
      - sh
      - lightning==2.2.*
      - torchmetrics==1.3.*

      # Hydra ecosystem
      - hydra-core==1.1.*
      - hydra-optuna-sweeper
      - hydra-colorlog
      - rootutils

      # Documentation tools
      - myst_parser==0.17.*
      - sphinxnotes-mock==1.0.0b0
      - sphinx_paramlinks==0.5.*

      # IGNF tools
      - ign-pdal-tools>=1.5.2

      # Experiment tracking (via pip to avoid conda conflicts)
      - comet_ml==3.35
