name: myria3d
channels:
  - pytorch
  - pyg
  - conda-forge
  - defaults
dependencies:
  - python=3.10  # Specify a stable version
  - pip
  
  # Core scientific computing
  - numpy=2.2
  - pandas=2.3
  - scipy=1.15
  
  # Geospatial and LiDAR
  - gdal=3.9
  - pdal=3.4
  - laspy=2.6
  - pyproj=3.6
  
  # Deep Learning (CPU versions for CI)
  - pytorch::pytorch=2.7
  - pytorch::torchvision
  - pytorch::torchaudio
  - pyg::pyg=2.6
  - pytorch-lightning=2.5
  - torchmetrics=1.8
  
  # Configuration and utilities
  - hydra-core=1.1
  - omegaconf=2.1
  - pyyaml=6.0
  - tqdm=4.67
  - click=8.2
  
  # Visualization
  - matplotlib=3.10
  - seaborn=0.13
  
  # Testing
  - pytest=8.4
  - pytest-cov=4.1
  - coverage=7.2
  
  # Development tools
  - black=25.1
  - flake8=7.3
  - isort=6.0
  
  - pip:
    # Any pip-only packages
    - hydra-colorlog==1.2.0
    - hydra-optuna-sweeper==1.2.0
    - rootutils==1.0.7