# ----------------------------------
# Hydra Lightning Template Makefile
# Extended for CUDA 12.8 + PyG setup
# ----------------------------------

help:  ## Show help
	@grep -E '^[.a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

# -----------------------------
# ENVIRONMENT MANAGEMENT
# -----------------------------

env:  ## Create the conda environment from environment.yml
	mamba env create -f environment.yml || conda env create -f environment.yml

torch:  ## Install PyTorch with CUDA 12.8 via pip
	pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cu128

torch:  ## Install PyTorch metrics
	pip install torchmetrics

pyg:  ## Install PyTorch Geometric and extensions via pip
	pip install torch_geometric pyg_lib torch_scatter torch_sparse torch_cluster torch_spline_conv -f https://data.pyg.org/whl/torch-2.7.0+cu128.html

install-full: env torch pyg ## Full environment setup: conda + torch + pyg

# -----------------------------
# CLEANING & FORMATTING
# -----------------------------

clean: ## Clean autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage

clean-logs: ## Clean logs
	rm -rf logs/**

format: ## Run pre-commit hooks
	pre-commit run -a

sync: ## Merge changes from main branch to your current branch
	git pull
	git pull origin main

# -----------------------------
# TESTING & TRAINING
# -----------------------------

test: ## Run not slow tests
	pytest -k "not slow"

test-full: ## Run all tests
	pytest

train: ## Train the model
	python src/train.py