defaults:
  - default.yaml

# Override 
finetune:
  _target_: src.callbacks.finetuning_callbacks.FinetuningFreezeUnfreeze
  d_in: ${model.d_in}
  num_classes: ${model.num_classes}
  unfreeze_fc_end_epoch: ???  # full end fc is unfrozen later than the last MLP.
  unfreeze_decoder_train_epoch: ???  # decoder is unfrozen later than last FC layer.