_target_: torch.nn.CrossEntropyLoss
label_smoothing: 0.0
ignore_index: 65  # artefacts are mapped to 65 by convention
weight:
  _target_: torch.FloatTensor
  _args_: 
    - ${dataset_description.class_weights}